# Generated by Django 4.2.16 on 2024-11-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.IntegerField(unique=True)),
                ('loan_amount', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('start_date', models.DateField()),
                ('term', models.IntegerField()),
                ('payment_frequency', models.CharField(max_length=20)),
                ('cpr', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanTape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('original_principal', models.FloatField()),
                ('amortization_term_month', models.IntegerField()),
                ('mortgage_term_month', models.IntegerField()),
                ('interest_rate', models.FloatField()),
                ('compounding_frequency', models.CharField(max_length=20)),
                ('payment_frequency', models.CharField(max_length=20)),
                ('cpr', models.FloatField()),
            ],
        ),
    ]
